feat: onRenderContextMenu context selection
josdejong/svelte-jsoneditor pull request #376
Opened 2023-12-21 12:47 UTC by 1pone

Using the context values `selection`, different actions can be taken depending on the path of selection.

2023-12-22 08:31 UTC, josdejong requested changes
Thanks, passing the `selection` along with onRenderContextMenu makes sense!

I made a couple of inline comments, can you have a look at those?

2023-12-22 08:31 UTC, josdejong commented on README.md
> +  - `onRenderContextMenu(items: ContextMenuItem[], context: { mode: 'tree' | 'text' | 'table', modal: boolean, selection?: JSONEditorSelection | null }) : ContextMenuItem[] | undefined`.
I think the definition should be without a question mark:

```
, selection: JSONEditorSelection | null }
```

2023-12-22 08:31 UTC, josdejong commented on package.json
> +  "version": "0.21.2",
Can you leave the version untouched? That will be automatically increased when publishing a new version.

2023-12-22 08:31 UTC, josdejong commented on pnpm-lock.yaml
Can you please remove the yaml lock file?

2023-12-22 08:31 UTC, josdejong commented on src/routes/development/+page.svelte
> +    console.log('onRenderContextMenu',item, content)
Can you run `npm run format` to fix any linting issues?

2023-12-25 03:21 UTC, 1pone commented
done

2024-01-10 10:50 UTC, josdejong approved these changes

2024-01-10 10:50 UTC, josdejong commented
Thanks for the updates! Merging now.

2024-01-10 10:50 UTC, merged

2024-01-10 15:59 UTC, josdejong commented
Published now in `v0.21.2`. Thanks again.