Feat: Pass validation severity into UI
josdejong/svelte-jsoneditor pull request #416
Opened 2024-03-14 17:27 UTC by anlinguist

This PR addresses the following discussion and issue:
- https://github.com/josdejong/svelte-jsoneditor/discussions/369
- https://github.com/josdejong/svelte-jsoneditor/issues/148

Allows the validation error severity to be `warning` (yellow), `error` (red), or `info`(blue).

If the validation error table is collapsed, it uses the first validation error to determine the color to show.
If the validation error table is opened, each validation error will be the assigned color from the validator.
Also updated the hover color for each validation error.

2024-03-15 15:20 UTC, josdejong commented
Thanks Andrew! I'll review your PR next week.

2024-03-20 10:21 UTC, josdejong requested changes
Thanks a lot for working out this solution Andrew, this looks good. I made a couple of inline comments. Can you have a look at those?

2024-03-20 10:21 UTC, josdejong commented on src/lib/components/controls/ValidationErrorsOverview.svelte
> +            class="jse-validation-error {validationError.severity}"
I think it would be good to have a `jse-` prefix to prevent conflicts with classes from other frameworks like Bootstrap. (and similar to how you solved this in `ValidationErrorIcon.svelte`. 

However it makes sense to have a base class like `jse-validation-error`, and then three subclasses for the different severity, like `jse-validation-severity-error`, `jse-validation-severity-warning`, `jse-validation-severity-info`. These subclasses only need to alter the color. And then for consistency we can use the same class names in both the overview and the error icon. What do you think?

2024-03-20 10:21 UTC, josdejong commented on src/lib/components/modes/textmode/TextMode.svelte
> +      severity: validationError.severity,
You can use destructuring here to write this more compact, like `path` and `message` that come from `validationError` too:

```js
use destructure `const { path, message, severity } = validationError`
```

2024-03-20 10:21 UTC, josdejong commented on src/lib/components/controls/ValidationErrorsOverview.svelte
> +      <table class="jse-validation-errors-overview-collapsed {validationErrors[0].severity}">
Thinking aloud here: it would be nice to take the most severe severity here instead of the first. But this may be overengineering. What do you think?

2024-03-20 10:21 UTC, josdejong commented on src/lib/components/controls/ValidationErrorsOverview.scss
> +.error {
Can you update the example [`src/routes/examples/custom_validation`](https://github.com/josdejong/svelte-jsoneditor/blob/main/src/routes/examples/custom_validation/+page.svelte) to demonstrate the tree different severity levels?

2024-03-20 10:21 UTC, josdejong commented on src/lib/components/controls/ValidationErrorsOverview.scss
> +        filter: brightness(110%);
This works perfect for the `error` and `info` classes, but in case of `warning` the color difference is very large. Is it possible to have a bit more subtle color change in that case?

2024-03-20 10:21 UTC, josdejong commented on src/lib/components/controls/ValidationErrorsOverview.scss
> +        filter: brightness(110%);
I also noticed that the highlighting doesn't work when the overview is collapsed, can you have a look at that?

2024-03-27 05:17 UTC, anlinguist commented on src/lib/components/controls/ValidationErrorsOverview.scss
> +        filter: brightness(110%);
I can set the brightness to 105% on `jse-validation-warning`. Also, migration to use `jse-validation-` prefixes has fixed the issue where hover brightness wasn't applied to the collapsed error.

2024-03-27 05:20 UTC, anlinguist commented on src/lib/components/controls/ValidationErrorsOverview.svelte
> +            class="jse-validation-error {validationError.severity}"
makes sense. pushing a change soon that implements this

2024-03-27 05:23 UTC, anlinguist commented on src/lib/components/controls/ValidationErrorsOverview.svelte
> +      <table class="jse-validation-errors-overview-collapsed {validationErrors[0].severity}">
that's a good idea. also, instead of applying the class change to the table, I've changed it to apply to the row, and I'm taking advantage of the new class with `jse-validation-` prefix.

2024-03-27 05:24 UTC, anlinguist commented on src/lib/components/controls/ValidationErrorsOverview.svelte
> +      <table class="jse-validation-errors-overview-collapsed {validationErrors[0].severity}">
This also required a helper function `getValidationClass()`

2024-03-27 09:05 UTC, josdejong commented on src/lib/components/controls/ValidationErrorsOverview.svelte
> +      <table class="jse-validation-errors-overview-collapsed {validationErrors[0].severity}">
Nice 😎

2024-03-27 09:12 UTC, josdejong commented on src/lib/components/controls/ValidationErrorsOverview.scss
> +        filter: brightness(110%);
Thanks, the 105% looks nice!

2024-03-27 09:12 UTC, josdejong approved these changes

2024-03-27 09:14 UTC, josdejong commented
Thanks for the updates, this looks really good, both the code and the UI!

2024-03-27 09:16 UTC, josdejong commented
I see there is a linting issue, I'll fix that right after merging.

2024-03-27 09:20 UTC, merged

2024-03-27 09:27 UTC, josdejong commented
After merging I thought it would be neat to rename the helper function `getValidationClass` to `getMaxSeverity`, I've changed that in 2c88d93648b25b193f9052ae365d9cd7152c0fa6.

2024-03-28 08:09 UTC, josdejong commented
Published now in `v0.23.1`, thanks again!